// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20201030172359_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 7,
                            Breed = "Tortoiseshell",
                            Color = "Black/Brown",
                            Gender = "Female",
                            Name = "Bijou"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 10,
                            Breed = "Ragamuffin",
                            Color = "Grey",
                            Gender = "Male",
                            Name = "George"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 13,
                            Breed = "Short-Hair",
                            Color = "Black",
                            Gender = "Female",
                            Name = "Ebe"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 4,
                            Breed = "Ragamuffin",
                            Color = "Orange/White",
                            Gender = "Female",
                            Name = "White Shoes"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 1,
                            Breed = "Ragamuffin",
                            Color = "Orange",
                            Gender = "Female",
                            Name = "Peachy Cat"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 6,
                            Age = 7,
                            Breed = "Labrador",
                            Color = "Yellow",
                            Gender = "Male",
                            Name = "Comet"
                        },
                        new
                        {
                            DogId = 7,
                            Age = 10,
                            Breed = "Labrador",
                            Color = "Yellow",
                            Gender = "Female",
                            Name = "Lizzie"
                        },
                        new
                        {
                            DogId = 8,
                            Age = 4,
                            Breed = "Pug",
                            Color = "Black",
                            Gender = "Female",
                            Name = "Georgia"
                        },
                        new
                        {
                            DogId = 9,
                            Age = 10,
                            Breed = "Unknown",
                            Color = "Black/Grey",
                            Gender = "Male",
                            Name = "Ruffin"
                        },
                        new
                        {
                            DogId = 10,
                            Age = 6,
                            Breed = "Rottweiler",
                            Color = "Black/Brown",
                            Gender = "Male",
                            Name = "Sir"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
